# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-06 10:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('star', models.FloatField()),
                ('attribute', models.CharField(max_length=200)),
                ('comment_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('text', models.CharField(max_length=200)),
                ('star', models.FloatField()),
                ('business', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user.Business')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('img_url', models.CharField(default=None, max_length=50)),
                ('caption', models.CharField(default=None, max_length=200)),
                ('label', models.CharField(default=None, max_length=50)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Business')),
            ],
        ),
        migrations.CreateModel(
            name='Recommend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user.Business')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='recommend',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
    ]
