# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-06 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='photo',
            name='img_url',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='photo',
            name='label',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
