# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-06 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20180506_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='average_stars',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='comment_count',
            field=models.IntegerField(default=0),
        ),
    ]
