# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-26 06:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20180426_1117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='name',
            new_name='img_url',
        ),
        migrations.AlterField(
            model_name='comment',
            name='data',
            field=models.DateTimeField(verbose_name=datetime.datetime(2018, 4, 26, 6, 9, 40, 619750, tzinfo=utc)),
        ),
    ]
