# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-26 06:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20180426_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='data',
        ),
        migrations.AddField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 26, 6, 47, 24, 744409, tzinfo=utc)),
        ),
    ]
