# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-07 00:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20180506_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='img_url',
        ),
        migrations.AddField(
            model_name='photo',
            name='img_data',
            field=models.TextField(default=None),
        ),
    ]
